### ISSUE TITLE
JSR and Client Side Rendering with gfm

### ISSUE THREAD

**Issue by mcgear** [denoland/deno-gfm#126]
https://github.com/denoland/deno-gfm/issues/119

We use esbuild to compile a control that is delivered to the client.  This was previously working, we just upgraded to JSR and now with the latest version of GFM (0.8.2), we are getting error:

```
Error: Dynamic require of "path" is not supported
    at eacIslandsClient.js?revision=1723577690368:12:9
    at ../../../../../../AppData/Local/deno/deno_esbuild/postcss@8.4.41/node_modules/postcss/lib/map-generator.js (map-generator.js:4:43)
    at __require2 (eacIslandsClient.js?revision=1723577690368:18:50)
    at ../../../../../../AppData/Local/deno/deno_esbuild/postcss@8.4.41/node_modules/postcss/lib/lazy-result.js (lazy-result.js:4:20)
    at __require2 (eacIslandsClient.js?revision=1723577690368:18:50)
    at ../../../../../../AppData/Local/deno/deno_esbuild/postcss@8.4.41/node_modules/postcss/lib/postcss.js (postcss.js:5:18)
    at __require2 (eacIslandsClient.js?revision=1723577690368:18:50)
    at ../../../../../../AppData/Local/deno/deno_esbuild/sanitize-html@2.13.0/node_modules/sanitize-html/index.js (index.js:6:33)
    at __require2 (eacIslandsClient.js?revision=1723577690368:18:50)
    at https://jsr.io/@deno/gfm/0.7.0/mod.ts (mod.ts:8:26)
```

We are in the process of checking older version to see if they work, 0.7.0 does not seem to work either.

**Comment by mcgear** [comment]
Uppon further look, it seems the render is working. The issue happens in mod.ts at this line:
```
import sanitizeHtml from "npm:sanitize-html@^2.11";
```

**Comment by jpsullivan** [comment]
Yep seeing the same thing over here while attempting to integrate into a small Fresh app.
