### ISSUE TITLE
Uncaught TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by justjavac** [denoland/deno-gfm#13]
```bash
> deno run --reload https://deno.land/x/gfm@0.1.22/example/main.ts
error: Uncaught TypeError: Cannot convert object to primitive value
    at String (<anonymous>)
    at Ft (https://esm.sh/v88/htmlparser2@6.1.0/deno/htmlparser2.js:3:20007)
    at https://esm.sh/v88/htmlparser2@6.1.0/deno/htmlparser2.js:3:21160
    at https://esm.sh/v88/htmlparser2@6.1.0/deno/htmlparser2.js:3:22507
    at https://esm.sh/v88/htmlparser2@6.1.0/deno/htmlparser2.js:2:1107
    at https://esm.sh/v88/htmlparser2@6.1.0/deno/htmlparser2.js:3:25511
    at https://esm.sh/v88/htmlparser2@6.1.0/deno/htmlparser2.js:2:1107
    at https://esm.sh/v88/htmlparser2@6.1.0/deno/htmlparser2.js:3:25658
```

**Comment by LeoDog896** [comment]
I think this issue is caused by it not working outside of the local filesystem. I'll see if I can fix this.
