### ISSUE TITLE
cpp code block throws error

### ISSUE THREAD

**Issue by raashidanwar** [denoland/deno-gfm#136]
I am trying to use the cpp code block but getting bellow error

```typescript
import { Handlers, PageProps } from "$fresh/server.ts";
import { CSS, render } from "jsr:@deno/gfm";
import "npm:prismjs@1.29.0/components/prism-cpp.js";
```

```
error: Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'class-name')
    at Object.extend (file:///deno/npm/registry.npmjs.org/prismjs/1.29.0/prism.js:345:16)
    at file:///deno/npm/registry.npmjs.org/prismjs/1.29.0/components/prism-cpp.js:6:40
    at Object.<anonymous> (file:///deno/npm/registry.npmjs.org/prismjs/1.29.0/components/prism-cpp.js:99:2)
    at Object.<anonymous> (file:///deno/npm/registry.npmjs.org/prismjs/1.29.0/components/prism-cpp.js:101:4)
```

**Comment by raashidanwar** [comment]
Got the fix.
I was looking at the code then I found basically we need to use c as well, cpp one is extending the style of c.

```typescript
import { Handlers, PageProps } from "$fresh/server.ts";
import { CSS, render } from "jsr:@deno/gfm";
import "npm:prismjs@1.29.0/components/prism-c.js";
import "npm:prismjs@1.29.0/components/prism-cpp.js";
```
